## Regularized regression models (toy example)

We try out the basic least-squares linear regression and some regularized linear regression models: ridge, lasso, elastic net.

In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet

We make some synthetic data: first we generate a 100-dimensional feature matrix with 100,000 instances, all normally distributed. We then form the output variable as a simple linear relation, by taking 0.4 times the first feature and -1.8 times the second feature. We then add a bit of noise.

As you see, the first two features are the only ones that are actually used. Let's see if the various regression models can discover this fact.

In [2]:
X = np.random.normal(size=(100000, 100))
Y = 0.4*X[:,0] - 1.8*X[:,1] + 0.5*np.random.normal(size=100000)

The standard least-squares regression model comes fairly close to recovering the true weights (0.4 and -1.8). All the other weights are fairly small, although not strictly zero.

In [3]:
lr = LinearRegression()
lr.fit(X, Y)
lr.coef_

array([ 3.99861120e-01, -1.79870999e+00,  4.09801865e-04, -7.77142019e-05,
       -5.95979833e-04, -3.55523868e-04,  2.74448477e-03, -2.14567456e-04,
        1.82302810e-03,  8.95017828e-04,  3.59197741e-04, -1.83229444e-03,
       -5.56508732e-04, -3.13190959e-03,  2.36814611e-04,  1.53794733e-03,
       -5.57476041e-04,  2.03787723e-03, -5.15177094e-04, -2.58767879e-03,
       -1.29546167e-03,  9.31374116e-04,  1.72916006e-03, -3.22871677e-03,
        2.49172669e-04, -2.43897290e-03,  1.56439456e-03, -1.36145746e-03,
        1.48637629e-03, -1.11657884e-03, -1.49513845e-03, -1.65840856e-03,
        3.23048381e-03, -1.31359891e-03,  3.04642137e-04,  1.07769223e-03,
       -8.70119885e-04,  1.52318172e-03, -7.48659080e-04,  2.46027826e-03,
       -4.74523397e-05,  8.11414225e-05, -2.03639892e-03,  2.28213696e-03,
       -4.17092557e-03, -5.91108621e-04, -8.44738542e-04,  3.28874681e-04,
        3.63375456e-04, -2.00934091e-03,  1.12425707e-03,  2.14354690e-03,
        1.20086695e-03,  

The same holds for the ridge regression (least squares plus L2 regularization). If you want, you can play around with the strength of the regularizer (`alpha`) and see how this affects the first two coefficients.

In [4]:
ridge = Ridge(alpha=10000)
ridge.fit(X, Y)
ridge.coef_

array([ 3.62955165e-01, -1.63543226e+00,  4.88006942e-04, -2.96481455e-04,
       -9.77113426e-05,  4.90174088e-05,  1.97116835e-03,  7.29761399e-05,
        2.13066620e-03,  9.44642829e-04,  1.45553134e-04, -1.96236496e-03,
        2.97191992e-05, -2.56285245e-03, -4.45744986e-04,  1.07975065e-03,
       -5.60084089e-04,  2.03863699e-03, -6.81149959e-04, -2.61413988e-03,
       -7.76151166e-04,  8.69426499e-04,  1.58345278e-03, -2.04250321e-03,
        8.45514749e-04, -2.02341020e-03,  1.89360109e-03, -1.82310579e-03,
        1.37451138e-03, -1.00838192e-03, -1.71113229e-03, -1.24929209e-03,
        2.94781649e-03, -1.59216433e-03,  3.34917966e-05,  1.31302106e-03,
       -1.31202481e-03,  1.33170785e-03, -8.91199998e-04,  2.35670292e-03,
       -4.41206032e-04,  3.81598975e-06, -1.86315853e-03,  1.91695244e-03,
       -3.83386837e-03, -1.13775815e-03, -7.90450537e-04,  4.18806341e-04,
        4.89504252e-05, -2.08715833e-03,  9.48981400e-04,  9.86281153e-04,
        1.15648659e-03,  

When we try out the Lasso (least squares plus L1 regularization), we clearly see the effect of the feature selection property of the Lasso: it has set most of the coefficients to exactly zero.

With the default value of `alpha` (which is 1), it seems we get a case of underfitting, because the Lasso has turned off the first feature. If we reduce it a bit, we more or less recover the true weights of the two first features and set all others to zero. (If we reduce it too much, non-zero elements will start to appear.)

In [5]:
lasso = Lasso(alpha=0.01)
lasso.fit(X, Y)
lasso.coef_

array([ 0.38982011, -1.78865771,  0.        , -0.        , -0.        ,
       -0.        ,  0.        , -0.        ,  0.        ,  0.        ,
        0.        , -0.        , -0.        , -0.        ,  0.        ,
        0.        , -0.        ,  0.        , -0.        , -0.        ,
       -0.        ,  0.        ,  0.        , -0.        ,  0.        ,
       -0.        ,  0.        , -0.        ,  0.        , -0.        ,
       -0.        , -0.        ,  0.        , -0.        ,  0.        ,
        0.        , -0.        ,  0.        , -0.        ,  0.        ,
        0.        ,  0.        , -0.        ,  0.        , -0.        ,
       -0.        , -0.        ,  0.        ,  0.        , -0.        ,
        0.        ,  0.        ,  0.        ,  0.        , -0.        ,
       -0.        , -0.        ,  0.        ,  0.        , -0.        ,
        0.        ,  0.        , -0.        ,  0.        ,  0.        ,
        0.        , -0.        ,  0.        ,  0.        , -0.  

The Elastic Net model uses a combination of L1 and L2 regularization. It has a feature selection effect similar to the Lasso.

In [6]:
en = ElasticNet(alpha=0.01, l1_ratio=0.5)

en.fit(X, Y)
en.coef_

array([ 0.39283957, -1.78475843,  0.        , -0.        , -0.        ,
       -0.        ,  0.        , -0.        ,  0.        ,  0.        ,
        0.        , -0.        , -0.        , -0.        ,  0.        ,
        0.        , -0.        ,  0.        , -0.        , -0.        ,
       -0.        ,  0.        ,  0.        , -0.        ,  0.        ,
       -0.        ,  0.        , -0.        ,  0.        , -0.        ,
       -0.        , -0.        ,  0.        , -0.        ,  0.        ,
        0.        , -0.        ,  0.        , -0.        ,  0.        ,
       -0.        ,  0.        , -0.        ,  0.        , -0.        ,
       -0.        , -0.        ,  0.        ,  0.        , -0.        ,
        0.        ,  0.        ,  0.        ,  0.        , -0.        ,
       -0.        , -0.        ,  0.        ,  0.        , -0.        ,
        0.        ,  0.        , -0.        ,  0.        ,  0.        ,
        0.        , -0.        ,  0.        ,  0.        , -0.  